apps/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('listagem/', views.listagem, name='listagem'),
    path('consulta/', views.consulta, name='consulta'),
]

banks/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers

from apps.core.api import viewsets as listbanksviewset

route = routers.DefaultRouter()

route.register(r'books', listbanksviewset.listbanksViewSet, basename="Bancos")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(route.urls)),
    path('', include('core.urls', namespace='home')),
]

apps/core/models.py
from django.db import models

# Create your models here.
class listbanks(models.Model):

    cod_compensacao = models.PositiveSmallIntegerField('Código de Compensação', primary_key=True, unique=True)
    nome_instituicao = models.CharField('Nome da Instituição', max_length=150)

    class Meta:
        verbose_name = 'Banco'
        verbose_name_plural = 'Bancos'
        ordering = ['cod_compensacao']

    def __str__(self):
        return self.nome_instituicao

apps/core/views.py
from django.contrib import messages

from django.shortcuts import render

from .models import listbanks

# Create your views here.
def home(request):
    template_name = 'base.html'
    return render(request, template_name, {})

def listagem(request):
    template_name = 'listagem.html'
    bancos = listbanks.objects.all()
    context = {'bancos': bancos}

    return render(request, template_name, context)

def consulta(request):
    template_name = 'consulta.html'
    search = request.GET.get('search')
    if search=='':
        search = 0
        messages.warning(request, 'Digite um Numero!')

    bancos = listbanks.objects.filter(cod_compensacao=search)
    print(bancos)

    if search in bancos:
        messages.error(request, 'Banco não Encontrado!')
        print(bancos)
    
    context = {'bancos': bancos}

    return render(request, template_name, context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Bancos</title>
</head>
<body>
    <div class="bodyhome">
        <div class="container">
            <div class="boxvidro">
                <h1>API Consulta de Bancos</h1>
                <br>
                <div class="row">
                </div>
                <br>
                <p>
                    Escolha uma Opção:
                </p>
                <div class="row">
                    <a href="{% url 'home:listagem' %}" class="btn btn-primary btn-lg btn-block">Listar Bancos</a>
                    <a href="{% url 'home:consulta' %}" class="btn btn-dark btn-lg btn-block">Consultar Banco</a>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    
</body>
</html>

templates/consulta.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    

    <title>Consulta API</title>
</head>
<body>
    <div class="container">
        <br>
            {% for m in messages %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ m }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}
        <br>
        <div class="row">
            <H1>Consulta de Intuições Bancárias</H1>
        </div>
        <div class="d-flex flex-row-reverse bd-highlight">
            <form class="form-inline my-0 my-lg-3" id="search-form">
                <input class="form-control mr-sm-2" type="number" placeholder="Digite o código do Banco" aria-label="Search" name="search" placeholder="Digite o código do Banco">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
            <table class="table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Código de Compensação</th>
                    <th scope="col">Nome da Instituição</th>
                </tr>
                </thead>
                <tbody>
                {% for banco in bancos %}
                    <tr>
                    <td>{{ banco.cod_compensacao }}</td>
                    <td>{{ banco.nome_instituicao }}</td>
                    </tr>      
                {% endfor %}
                </tbody>
            </table>
            <BR></BR>
            <div class="d-flex flex-row-reverse bd-highlight">
                <div class="row">
                    <div class="bnt-group">
                        <a href="{% url 'home:home' %}" class="btn btn-primary">Início</a>
                        <a href="{% url 'home:listagem' %}" class="btn btn-secondary">Listagem</a>
                    </div>
                </div>
            </div>
    </div>

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/listagem.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    

    <title>Bancos</title>
</head>
<body>
<div class="container">
    <br>
    <div class="row">
        <h1>Bancos:</h1>
    </div>
    <div class="d-flex flex-row-reverse bd-highlight">
        <div class="row">
            <div class="bnt-group">
                <a href="{% url 'home:home' %}" class="btn btn-primary">Início</a>
                <a href="{% url 'home:consulta' %}" class="btn btn-secondary">Consulta</a>
            </div>
        </div>
    </div>
    <br>
    <table class="table table-striped">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Código de Compensação</th>
            <th scope="col">Nome da Instituição</th>
        </tr>
        </thead>
        <tbody>
        {% for banco in bancos %}
            <tr>
            <td>{{ banco.cod_compensacao }}</td>
            <td>{{ banco.nome_instituicao }}</td>
            </tr> 
        {% endfor %}
        </tbody>
    </table>
   <br>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>